### ISSUE TITLE
Import-D365ExternalUser doesn't respect language

### ISSUE THREAD

**Issue by AndrewJonesA1X** [d365collaborative/d365fo.tools#391] opened 2020-03-12 23:32 UTC
Hi all

I have been making good use of Import-D365ExternalUser, and specifying en-gb as the -Language parameter. However the users are always created with en-us.

Is somebody able to replicate?

Thanks
Andrew Jones

**Comment by Splaxi** [comment] 2020-03-13 10:08
I've located where the issue is.

The parameter isn't passed down to the internal functions/cmdlets. On top of that, they don't expect it either.

So we need to extend the internal stuff first, and wire the import cmdlet to pass it down. 

I hope to have something in the next 2 weeks or so.

If you want, I can guide you and then you can see if you can fix it yourself 😉

**Comment by AndrewJonesA1X** [comment] 2020-03-13 10:11
Thanks Mötz

Nah if it’s not x++ I’ll let you sort it out!!

Cheers
Andrew

**Comment by Splaxi** [comment] 2020-03-13 10:55
Fair enough - I feel the same way, but the other way around. If it is X++, I'll let you other guys handle that 🤣

**Comment by Splaxi** [comment] 2020-03-16 20:14
Should be fixed in 0.5.80 (will be released in 15-20 minutes)

**Closed by Splaxi** 2020-03-16 20:14 UTC
