### ISSUE TITLE
New-D365Bacpac with CustomSqlFile

### ISSUE THREAD

**Issue by fhoo** [d365collaborative/d365fo.tools#279] opened 2019-05-21 12:59 UTC
When calling New-D365Bacpac with the -CustomSqlFile parameter, the command aborts after calling the custom script.
The reason is, that Invoke-D365SqlScript never returns a value:
https://github.com/d365collaborative/d365fo.tools/blob/2155fde5b80e72bfe6765e3efcf576645ff5b5b2/d365fo.tools/functions/new-d365bacpac.ps1#L205

so the if statement is always true:
https://github.com/d365collaborative/d365fo.tools/blob/2155fde5b80e72bfe6765e3efcf576645ff5b5b2/d365fo.tools/functions/new-d365bacpac.ps1#L207

**Comment by Splaxi** [comment] 2019-05-22 03:47
Thank you for reporting the issue!

You are spot on what the issue is.

Would you be willing to try and edit the code on your side, to see if things work, before pushing the change? I don't have an environment to test against these days because I'm with a customer...

**Comment by Splaxi** [comment] 2019-05-22 03:49
Line 207 should be
```
if (Test-PSFFunctionInterrupt) { return }
```

**Comment by fhoo** [comment] 2019-05-22 07:48
I tested the suggested change and it works like expected.

**Comment by Splaxi** [comment] 2019-05-22 20:46
Should be fixed in 0.5.36

**Closed by Splaxi** 2019-05-22 20:46 UTC
