### ISSUE TITLE
8.1/PU20 Cloud VM - Import-D365AadUser

### ISSUE THREAD

**Issue by Shind44** [d365collaborative/d365fo.tools#63] opened 2018-10-03 08:03 UTC
Hello,

Import-D365AadUser seems to not working on a fresh 8.1/PU20 Cloud deployement VM

> AOS Path is not retrieve correclty by the module and so it try to load DLL from c:\bin\XXX.DLL and 
necessarily, that's not working.

PS C:\windows\system32> Import-D365AadUser -AadGroupName "MYGROUP"  -StartupCompany USMF -DatabaseServer localhost -DatabaseName AxDB -SqlUser axdbadmin -SqlPwd "MYPWD" -Verbose

VERBOSE: [07:02:53][Test-TrustedConnection] Not capable of using Trusted Connection based on supplied SQL login details.
VERBOSE: [07:02:53][Get-SqlCommand] Building the SQL connection string.
Add-Type : Cannot bind parameter 'Path' to the target. Exception setting **"Path": "Cannot find path 'C:\bin\Microsoft.Dynamics.AX.Framework.EncryptionEngine.dll'** because it does not exist."
At line:5 char:24
+ ... -Type -Path **"$Script:AOSPath\bin\Microsoft.Dynamics.AX.Framework.Encr ...**
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Add-Type], ParameterBindingException
    + FullyQualifiedErrorId : ParameterBindingFailed,Microsoft.PowerShell.Commands.AddTypeCommand

Add-Type : Cannot bind parameter 'Path' to the target. Exception setting "Path": "Cannot find path 'C:\bin\Microsoft.Dynamics.AX.Framework.EncryptionEngine.dll' because it does not exist."
At line:5 char:24
+ ... -Type -Path "$Script:AOSPath\bin\Microsoft.Dynamics.AX.Framework.Encr ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Add-Type], ParameterBindingException
    + FullyQualifiedErrorId : ParameterBindingFailed,Microsoft.PowerShell.Commands.AddTypeCommand

**Comment by Splaxi** [comment] 2018-10-03 08:18
Could you please run the following command:

Get-PSFMessage -Level Verbose | Format-List | Out-file c:\temp\d365-results.txt

Please share the file on pastebin or similar page and post the link in this thread.

**Comment by Splaxi** [comment] 2018-10-03 10:10
It seems odd.

Could you play around with the "Get-D365EnvironmentSetting" cmdlet a bit. It should return a memory object that should contain all information about the environment that you're running on.

Another test should be to execute this inside a powershell
Join-Path ([System.Environment]::ExpandEnvironmentVariables("%ServiceDrive%")) "\AOSService\webroot\bin"

The result should give you a valid path to the AOS. Could you please confirm that?

**Comment by Splaxi** [comment] 2018-10-03 10:18
When you run the following:

Get-PSFMessage

You should get the below picture.

![image](https://user-images.githubusercontent.com/8750181/46404703-453a9b00-c706-11e8-8e69-9153d47f79bc.png)

Can you see if there is anything filled out for the "$Script:AOSPath:" entry?

**Comment by Splaxi** [comment] 2018-10-03 11:32
I'll have to dig into it.

You could check the wiki on how to find the install path of the module.

In that you should be able to find the "Get-ApplicationEnvironment.ps1" file. Inside that you should see a list of different assemblies. Try and see if they exist or not on the location that we assume.

**Comment by Splaxi** [comment] 2018-10-03 11:33
Could you please execute the below:

Get-D365EnvironmentSetting

And share if there is any output at all?

**Comment by Shind44** [comment] 2018-10-04 07:46
Result 

![image](https://user-images.githubusercontent.com/40988263/46459674-e171aa00-c7b9-11e8-9254-a316e3bd7125.png)

Microsoft.Web.Administration.dll seems to be not present anymore  (8.1) in webroot\bin directory
powershell failed when trying to shadow copy this dll

**Comment by devax** [comment] 2018-10-04 07:59
I had the same issue on our local VPCs (8.0/PU15), while it was working well on the Azure machines.

I tracked it down a bit and I think the problem is second line in file internal/functions/get-applicationenvironment.ps1:
`$AOSPath = Join-Path ([System.Environment]::ExpandEnvironmentVariables("%ServiceDrive%")) "\AOSService\webroot\bin"`

This relys on the environment variable %ServiceDrive% being set to "C:" (on local VPCs). This environment variable was not set on our local VPCs. After I have manually created it, things started to work.

**Comment by Shind44** [comment] 2018-10-04 08:00
@devax  : for me it was on fresh Cloud VM that the problem occurs

**Comment by devax** [comment] 2018-10-04 08:10
Is the environment variable set on your VM? Does
`[System.Environment]::ExpandEnvironmentVariables("%ServiceDrive%")`
return anything?

**Comment by Shind44** [comment] 2018-10-04 08:12
Yes, and the good value

![image](https://user-images.githubusercontent.com/40988263/46461084-0ec05700-c7be-11e8-818d-bcd2d2cea7c9.png)

**Comment by Splaxi** [comment] 2018-10-04 11:53
@Shind44 

Please locate this file using a search tool:

**Microsoft.Dynamics.ApplicationPlatform.Environment.dll**

[UltraSearch portable ](https://www.jam-software.de/customers/downloadTrial.php?article_no=670&language=EN) is recommended for that. If you have Local Administrator privileges, it will scan your disk in less than a minute.

Next step is that you and me have a session using some remote tools, so I can peek into the system that you are on.

**Comment by Shind44** [comment] 2018-10-04 12:14
Mötz, below the result of the command
![image](https://user-images.githubusercontent.com/40988263/46473183-92d70680-c7df-11e8-8084-70daf4fafdba.png)

no problem to make a remote session if needed

**Comment by Splaxi** [comment] 2018-10-04 13:12
I believe you should include all drives that exists on that machine.

Click on the plus sign next to **"C:\"** just above the results pane. There you should be able to check / select all drives / disk on the machine.

**Comment by syfhu** [comment] 2018-10-05 07:30
On a local 8.1/PU20 preview VM the file can be found in C:\Windows\System32\inetsrv\ 
Copying it to the AOSService\webroot\bin folder fixed the issue for me.
I haven't reported it yet, because it was a preview machine, but now it seems the file won't be where it is expected anymore.
An other question, haven't tried: do we still need to load that assembly?

**Comment by Splaxi** [comment] 2018-10-05 09:01
I really need to get access to a 8.1 environment to understand this a bit more. Even a preview would be very helpful 😀

**Comment by syfhu** [comment] 2018-10-05 10:48
I'm not getting any error in a 8.0/PU15 environment when I just omit loading the Microsoft.Web.Administration assembly. And on a first look the environment settings could be loaded successfuly. I currently don't have my 8.1 environment available to test it there..

**Comment by Splaxi** [comment] 2018-10-05 11:18
So Frank.

On a local tier 1 (vhd) 8.0 PU15 I have never had a problem with the current state of loading the files.

I'll dig into it things a bit more. "Someone" is lending me a box to work against for the 8.1 issues we are seeing.

Stay tuned as they say 😀

**Comment by syfhu** [comment] 2018-10-05 12:13
I had no issue on such an environment, neither. It's more that I'm suggesting, that we can completely omit loading the assembly in any environment, if we don't need it. And my test in the 8.0 environment was more like: what happens when the file is not loaded. If everything works without, we don't need to find a solution finding the file if it is not in the expected place in an 8.1 environment, but just change the script to skip loading the file and the tools are compatible with all versions 😎

**Comment by Splaxi** [comment] 2018-10-05 12:19
I understand what you are saying.

I can say that the early testing on 7.2 / 7.3 required that specific file, on Tier 1 local hosted VM's.

With that said, I will ensure that we really need it, but while loading the other assemblies there was a reference to it and our loading failed. They might have fixed this dependency in 8.0, but didn't remove the file.

We will know more in the near future 🤘

**Comment by syfhu** [comment] 2018-10-05 12:53
Ok, understand.
The oldest version I currently can access is a 7.3/PU12, and that is working without loading the Web.Administration assembly. And now I also tested on 8.1, which seems to have no issues with skipping that file, either. 
So if you have a 7.2 or 7.3 with an older PU you should check it there, too. But otherwise: versions before 7.3 will only be supported until April 2019, and PU12 is only supported until November 2018 😉

**Comment by Splaxi** [comment] 2018-10-05 13:37
Did you simply remove the code line where the file is referenced to the lists of files to load?

**Comment by ITRasmus** [comment] 2018-10-05 13:45
It sounds like the fix should be : load the file if it this there else just skip loading it.

**Comment by Splaxi** [comment] 2018-10-05 17:00
Okay - I learned something today. No solution just yet.

1. The Microsoft.Web.Administration.dll doesn't live inside the bin folder anymore.
   - The fun story is that it lives inside the GAC and have been since 7.2 ish. The reason why we loaded it earlier was because it was present in the bin folder. So that dependency can be removed.
2. From 8.1 on Azure hosted environments our execution of the "[Microsoft.Dynamics.ApplicationPlatform.Environment.EnvironmentFactory]::GetApplicationEnvironment()" doesn't decrypt the SqlPwd anymore. I haven't found the exact reason why.
   - The next fun part is that our "Get-D365DecryptedConfigFile" can decrypt the web.config file as expected and it contains the correct SqlPwd for the SqlUser.

I need some assistance from @ITRasmus to crack this one. I don't fully understand why the "Microsoft.Dynamics.AX.Framework.ConfigEncryptor.exe" is capable and the assemblies are not. 

There are 2 ways out of this, if we don't crack the dll's files issue.

1. We simply run the "Microsoft.Dynamics.AX.Framework.ConfigEncryptor.exe" on module load, have it store the config file in %temp%, traverse the web.config file for SqlPwd. It will extend the load time, but will make the module work like always.
2. We create a cmdlet / function that people have to execute the first time the module is installed. That will decrypt the web.config file, traverse it and load the SqlPwd into the PSF-Config configuration store. This will then be persisted for the next time the module is loaded and run. It needs some rework on some of the dependencies we have built into different cmdlets / functions in the module at this time.

So guys - Anyone of you smart enough to see what a given process is accessing of assemblies and files with some of the tools from sysinternals, that can look at a 8.0 and a 8.1, to see where the differences are?

**Comment by Splaxi** [comment] 2018-10-05 17:12
A quick note.

It seems that the Microsoft.Dynamics.AX.Framework.ConfigEncryptor.exe (via Microsoft.Dynamics.AX.Framework.EncryptionEngine.dll) just loads the config file, reads the 3-4 different thumbprints of the different certificates and "tries" to decrypt stuff.



If we learn what values are passed from the Microsoft.Dynamics.AX.Framework.ConfigEncryptor.exe to the methods inside Microsoft.Dynamics.AX.Framework.EncryptionEngine.dll, then  with some time and effort we should be able to do the same, without the need of the current dll's.

**Comment by Splaxi** [comment] 2018-10-09 22:48
Okay guys!

I finally spend some time on looking into the things a bit more.

I have a crude C# console application that can decode the config file on the fly. I'll work on making that into a C# class, that we can call from powershell. 

Down the road I'm going to dive into what changed in the dll files, because we might need to fake the most important part of it, to produce the expect output from:
`Get-D365EnvironmentSettings -> Get-ApplicationEnvironment -> [Microsoft.Dynamics.ApplicationPlatform.Environment.EnvironmentFactory]::GetApplicationEnvironment()`

**Comment by Splaxi** [comment] 2018-10-10 19:47
And we have a new release that should solve this issue.

@shind44 please try again 🤞

**Comment by Splaxi** [comment] 2018-10-11 09:00
So @syfhu did some preliminary testing and found no issues. I've done the same across several versions and machine types. 

Based on that, and the VERY long history in this issue, I will close it now. Please open a new one @Shind44 if things still doesn't work like expected. Then we can track down the missing pieces.

**Closed by Splaxi** 2018-10-11 09:00 UTC
